name: n8n push Release

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Bump version
      id: bump_version
      run: |
        chmod +x .github/scripts/bump-version.sh
        ./.github/scripts/bump-version.sh
      env:
        VERSION_BUMP_TYPE: ${{ github.event.inputs.version_bump_type }}

    - name: Commit version
      run: |
        git add n8n-push.sh
        git commit -m "chore(release): bump version to ${{ steps.bump_version.outputs.new_version }}"
        git push

  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: calculate-version
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref_name }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate changelog
      run: |
        chmod +x .github/scripts/generate-changelog.sh
        ./.github/scripts/generate-changelog.sh

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Commit changelog
      run: |
        git add CHANGELOG.md
        if ! git diff --staged --quiet; then
          git commit -m "docs(changelog): update for v${{ needs.calculate-version.outputs.new_version }}"
          git push origin HEAD:${{ github.ref_name }}
        fi

  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    needs: [calculate-version, generate-changelog]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Update badges
      run: |
        chmod +x .github/scripts/repo-badges.sh
        ./.github/scripts/repo-badges.sh

    - name: Commit badges
      run: |
        git add readme.md
        if ! git diff --staged --quiet; then
          git commit -m "docs(readme): update badges for v${{ needs.calculate-version.outputs.new_version }}"
          git push
        fi

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [calculate-version, generate-changelog, update-badges]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.calculate-version.outputs.new_version }}
        name: Release v${{ needs.calculate-version.outputs.new_version }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
